### ISSUE TITLE
DataBase Design for Patient Monitoring system

### ISSUE THREAD

**Issue by samanthameer** [ASJH/Project-1---Ward#6]
![Uploading DB Disign.gif…]()

**Comment by samanthameer** [comment]
![db disign](https://github-cloud.s3.amazonaws.com/assets/14921598/10566178/7bf8e2ce-75d7-11e5-8fe1-c6c4be836941.gif)

**Comment by ghost** [comment]
can this include the upper and lower settings aswell?
